
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb8\x8e\xcaU\xcb|"\xbe\x0b_R\xd0\xb0\xb2\xdb\x15'
    
_lr_action_items = {'TASK':([0,1,5,6,7,13,15,16,17,21,22,38,40,41,47,49,],[2,2,2,2,2,-9,-8,-7,-11,-10,-13,-15,-12,-14,-22,-23,]),'RPAREN':([13,15,33,],[-9,-8,40,]),'STRING':([2,3,4,9,24,25,27,32,37,46,],[13,13,13,13,13,13,13,13,13,13,]),'SCRIPT':([13,15,31,34,39,43,47,],[-9,-8,37,37,-18,-19,37,]),'NAMESPACE':([0,1,5,6,7,13,15,16,17,21,22,38,40,41,47,49,],[3,3,3,3,3,-9,-8,-7,-11,-10,-13,-15,-12,-14,-22,-23,]),'ACTOR':([0,1,5,6,7,13,15,16,17,21,22,38,40,41,47,49,],[4,4,4,4,4,-9,-8,-7,-11,-10,-13,-15,-12,-14,-22,-23,]),'BLOCKSTART':([13,15,42,],[-9,-8,44,]),'ROLE':([0,1,5,6,7,13,14,15,16,17,21,22,23,29,30,35,38,40,41,47,49,],[9,9,9,9,9,-9,25,-8,-7,-11,-10,-13,25,-20,25,-21,-15,-12,-14,-22,-23,]),'LPAREN':([13,15,17,],[-9,-8,27,]),'ACTION':([44,50,],[46,46,]),'BLOCKEND':([45,50,51,],[47,-24,-25,]),'DESCRIPTION':([13,14,15,29,48,],[-9,24,-8,24,50,]),'REQUIRES':([13,15,26,28,30,36,39,],[-9,-8,32,32,-16,-17,32,]),'ID':([2,3,4,9,24,25,27,32,37,46,],[15,15,15,15,15,15,15,15,15,15,]),'$end':([0,1,5,6,7,8,10,11,12,13,15,16,17,18,19,20,21,22,38,40,41,47,49,],[-26,-26,-26,-26,-26,-1,0,-6,-5,-9,-8,-7,-11,-4,-3,-2,-10,-13,-15,-12,-14,-22,-23,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'namespace_def':([0,1,5,6,7,],[1,1,1,1,1,]),'task_contents':([14,],[22,]),'task_descriptions':([14,29,],[23,35,]),'script_actions':([44,50,],[45,51,]),'task_scripts':([31,34,47,],[38,41,49,]),'task_def':([0,1,5,6,7,],[5,5,5,5,5,]),'actor_def':([0,1,5,6,7,],[6,6,6,6,6,]),'task_requirements':([26,28,39,],[31,34,43,]),'role_def':([0,1,5,6,7,],[7,7,7,7,7,]),'statement_list':([0,1,5,6,7,],[8,12,18,19,20,]),'document':([0,],[10,]),'id':([2,3,4,9,24,25,27,32,37,46,],[14,16,17,21,29,30,33,39,42,48,]),'empty':([0,1,5,6,7,],[11,11,11,11,11,]),'task_roles':([14,23,30,],[26,28,36,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> statement_list','document',1,'p_document','parse.py',14),
  ('statement_list -> role_def statement_list','statement_list',2,'p_statements','parse.py',17),
  ('statement_list -> actor_def statement_list','statement_list',2,'p_statements','parse.py',18),
  ('statement_list -> task_def statement_list','statement_list',2,'p_statements','parse.py',19),
  ('statement_list -> namespace_def statement_list','statement_list',2,'p_statements','parse.py',20),
  ('statement_list -> empty','statement_list',1,'p_statements','parse.py',21),
  ('namespace_def -> NAMESPACE id','namespace_def',2,'p_namespace_def','parse.py',24),
  ('id -> ID','id',1,'p_identifier','parse.py',27),
  ('id -> STRING','id',1,'p_identifier','parse.py',28),
  ('role_def -> ROLE id','role_def',2,'p_role_def','parse.py',32),
  ('actor_def -> ACTOR id','actor_def',2,'p_actor_def','parse.py',36),
  ('actor_def -> ACTOR id LPAREN id RPAREN','actor_def',5,'p_actor_def','parse.py',37),
  ('task_def -> TASK id task_contents','task_def',3,'p_task_def','parse.py',50),
  ('task_contents -> task_descriptions task_roles task_requirements task_scripts','task_contents',4,'p_task_contents','parse.py',59),
  ('task_contents -> task_roles task_requirements task_scripts','task_contents',3,'p_task_contents','parse.py',60),
  ('task_roles -> ROLE id','task_roles',2,'p_task_roles','parse.py',64),
  ('task_roles -> ROLE id task_roles','task_roles',3,'p_task_roles','parse.py',65),
  ('task_requirements -> REQUIRES id','task_requirements',2,'p_task_requirements','parse.py',75),
  ('task_requirements -> REQUIRES id task_requirements','task_requirements',3,'p_task_requirements','parse.py',76),
  ('task_descriptions -> DESCRIPTION id','task_descriptions',2,'p_task_descriptions','parse.py',86),
  ('task_descriptions -> DESCRIPTION id task_descriptions','task_descriptions',3,'p_task_descriptions','parse.py',87),
  ('task_scripts -> SCRIPT id BLOCKSTART script_actions BLOCKEND','task_scripts',5,'p_task_scripts','parse.py',92),
  ('task_scripts -> SCRIPT id BLOCKSTART script_actions BLOCKEND task_scripts','task_scripts',6,'p_task_scripts','parse.py',93),
  ('script_actions -> ACTION id DESCRIPTION','script_actions',3,'p_script_actions','parse.py',102),
  ('script_actions -> ACTION id DESCRIPTION script_actions','script_actions',4,'p_script_actions','parse.py',103),
  ('empty -> <empty>','empty',0,'p_empty','parse.py',116),
]
